user www-data;
worker_processes auto;
daemon off; # Don't run Nginx as a daemon, as we run it in Docker we need a foreground process.
events { }

http {
	server_names_hash_bucket_size 128;

	access_log /var/log/nginx_access.log;
	error_log /var/log/nginx_errors.log;

	server {
		listen 80;
		server_name localhost;
		location / {
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;

			proxy_connect_timeout 300;

			proxy_http_version 1.1;
			proxy_set_header Connection "";
			chunked_transfer_encoding off;
			
			proxy_pass http://rundeck:4440;
		}
	}

	# Denylist Google
	server {
    	listen   	80;
    	server_name  google.com;
    	server_name  *.google.com;
    	return 404;
	}


	# Everything else is allowed
	server {
    	  listen   	80;
    	  server_name ~.+;
    	  proxy_connect;
    	  proxy_max_temp_file_size 0;
    	  resolver 8.8.8.8;
    	  location / {
       	  proxy_pass http://$http_host;
       	  proxy_set_header Host $http_host;
    	  }
	}
}
