apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundeck
  labels:
    app: rundeck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rundeck
  template:
    metadata:
      labels:
        app: rundeck
    spec:
      containers:
      - name: rundeck
        image: rundeck:P4dmuNt2
        ports:
        - containerPort: 4440
      serviceAccountName: admin
      automountServiceAccountToken: true
