name: rophy/elasticsearch-a0
on:
  push:
    paths:
    - elasticsearch-a0/**
  pull_request:
    paths:
    - elasticsearch-a0/**
jobs:
  test:
    if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./elasticsearch-a0
        dockerfile: ./elasticsearch-a0/Dockerfile
        push: false
  build-and-push:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set variables
      run: |
        VER=$(cat elasticsearch-a0/version.txt)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./elasticsearch-a0
        dockerfile: ./elasticsearch-a0/Dockerfile
        push: true
        tags: rophy/elasticsearch-a0:${{ env.VERSION }}
